🔗: ディープリンクの検証とまとめ
ws-4020/react-native-sandbox pull request #1
Opened 2021-07-21 07:50 UTC by tani-takanori

## ✅ What's done

- [ ] 実装して検証したこと書く
- [ ] READMEにまとめていること書く

## What's not done

- [ ] 検証から外したこと、未検証なことを書く

2021-07-28 01:49 UTC, creature-water-valley commented on deep-links/README.md
> +## ユースケース
アプリのライフサイクル毎にURLを取得できるか検証したほうがいいかなぁと思いました。

* アプリを起動してない
* アプリがバックグラウンド
* アプリがフォアグラウンド

2021-07-28 01:51 UTC, creature-water-valley commented on deep-links/README.md
> +このとき、ユーザは最新のURLをアプリで受け取る必要があるが、古い（1回目）URLを取得する無効なURLを受けとってしまう。
これって、未インストールの場合のみに発生するんですかね？？

アプリはインストールされていて、異なるURLを2回連続とかでタップした場合は、ちゃんと取れますかね？

2021-07-28 01:56 UTC, creature-water-valley commented on deep-links/README.md
> +「ドメインの関連付け」を利用しないで実装、テストできるスコープは検証できていない。（URL作成には関連付けは不要なはず）
ドメインの関連付けをしないで、URL作成だけ動的にするユースケースがあまり思い浮かばないので、検証しなくてもいいんじゃないかなって思いました。

なんか、そのユースケースってありますかね？

2021-07-28 02:15 UTC, tani-takanori commented on deep-links/README.md
> +## ユースケース
onLinkの動作検証考えてみます

2021-07-28 02:15 UTC, tani-takanori commented on deep-links/README.md
> +このとき、ユーザは最新のURLをアプリで受け取る必要があるが、古い（1回目）URLを取得する無効なURLを受けとってしまう。
はい。

LinkingでListenしてResolveLinkでできないか検証してみます。

2021-07-28 02:18 UTC, tani-takanori commented on deep-links/README.md
> +「ドメインの関連付け」を利用しないで実装、テストできるスコープは検証できていない。（URL作成には関連付けは不要なはず）
アプリのユースケース的にはないんですが、開発フェーズでURL作成する画面実装する人（今回だとQRコードを作成する人）のデバイス登録やFirebaseの設定ファイルが必要になってしまうかどうか検証しようと思っていました。

2021-07-28 02:19 UTC, tani-takanori commented on deep-links/README.md
> +「ドメインの関連付け」を利用しないで実装、テストできるスコープは検証できていない。（URL作成には関連付けは不要なはず）
QRコードを読み取って招待コードを画面に入れる人は必要なのは確か

2021-07-29 02:24 UTC, in-a-paddy requested changes

2021-07-29 02:24 UTC, ghost commented on deep-links/README.md
> +# ディープリンク
フォルダ構成をErrorHandlingと合わせてもらいたいな

2021-07-29 02:24 UTC, ghost commented on deep-links/README.md
> +Dynamic Linksを利用して「アプリケーションのURLの作成」と「URLからアプリを起動できる設定」を検証する。
アプリケーションのURLって、アプリケションを開くURLのことであってる？

```suggestion
Dynamic Linksを利用して「アプリケーションを開くURLの作成」と「URLからアプリを起動できる設定」を検証する。
```

2021-07-29 02:24 UTC, ghost commented on deep-links/README.md
> +ドメインの関連付けがiOSは高度な機能のためADPライセンスを利用する。
```suggestion
iOSでのドメインの関連付け（[Associated Domains](https://help.apple.com/developer-account/?lang=ja#/dev21218dfd6)）は高度な機能に含まれるため、ADPライセンスを利用する。
```

2021-07-29 02:24 UTC, ghost commented on deep-links/README.md
> +- 未インストール時はAndriodはAzure Blob StorageにてAPKファイル、iOSはTestFlightに遷移してインストール後に起動してもらう。
```suggestion
- 未インストール時はAndroidはAzure Blob StorageにてAPKファイル、iOSはTestFlightに遷移してインストール後に起動してもらう。
```

2021-07-29 02:43 UTC, tani-takanori commented on deep-links/README.md
> +Dynamic Linksを利用して「アプリケーションのURLの作成」と「URLからアプリを起動できる設定」を検証する。
あってます

2021-07-29 02:44 UTC, tani-takanori commented on deep-links/README.md
> +- 未インストール時はAndriodはAzure Blob StorageにてAPKファイル、iOSはTestFlightに遷移してインストール後に起動してもらう。
これSASだとURLが変わるのでDeploy Gate利用するように修正します。

2021-07-29 04:39 UTC, tani-takanori commented on deep-links/README.md
> +# ディープリンク
フォルダ構成直しました

2021-08-02 01:37 UTC, creature-water-valley commented on DynamicLinksSandbox/README.md
> +- インストール後に別のURLを利用
これって、未検証なんでしたっけ？
検証したけど、想定通りの結果にはならなかった（1回目のURLしか取れない）じゃなかったでしたっけ？

2021-08-02 01:42 UTC, tani-takanori commented on DynamicLinksSandbox/README.md
> +- インストール後に別のURLを利用
そうでした。修正します。

2021-08-02 01:59 UTC, creature-water-valley commented on DynamicLinksSandbox/src/screens/deeplink/DeepLink.tsx
> +                onPress={() => Linking.openURL(createdLink)}
タップすると、ブラウザが開いちゃうんですけどこれはなんでですかね？
イメージ的には、アプリはフォアグラウンドのままで、ページ遷移だけするイメージだったんですが。

2021-08-02 02:32 UTC, creature-water-valley commented on deep-links/README.md
> +# ディープリンク
プロジェクト名のサフィックスもなしだとエラーハンドリングと同じで良いなぁと。。。

2021-08-02 04:18 UTC, tani-takanori commented on deep-links/README.md
> +# ディープリンク
https://github.com/ws-4020/react-native-sandbox/pull/1/commits/7c114d8ac7e9b1ff865a600b0d4632651429e63f
https://github.com/ws-4020/react-native-sandbox/pull/1/commits/fe8760db5b76438b5f88b1d71a96fe50cab5f831
https://github.com/ws-4020/react-native-sandbox/pull/1/commits/0a54a26d6aaa697d905cd26e69a4188cee0fc086
プロジェクトとか名前を`DeepLink` に変更しました

2021-08-02 05:25 UTC, tani-takanori commented on deep-links/README.md
> +- 未インストール時はAndriodはAzure Blob StorageにてAPKファイル、iOSはTestFlightに遷移してインストール後に起動してもらう。
https://github.com/ws-4020/react-native-sandbox/pull/1/commits/5335eaf9816bf01e8e239c3fc459a2b40f98fb0b

2021-08-02 05:26 UTC, tani-takanori commented on DynamicLinksSandbox/README.md
> +- インストール後に別のURLを利用
検証済みなので修正しました。
in-a-paddyさんからケース読み解けないって指摘あったのでケースも修正しました

https://github.com/ws-4020/react-native-sandbox/pull/1/commits/f278830d01be7951aba75a2c5abf7e5da8bc51bf

2021-08-02 05:27 UTC, tani-takanori commented on DynamicLinksSandbox/src/screens/deeplink/DeepLink.tsx
> +                onPress={() => Linking.openURL(createdLink)}
ちょっとテストしてます
https://github.com/ws-4020/react-native-sandbox/pull/1

2021-08-02 05:28 UTC, tani-takanori commented on DynamicLinksSandbox/src/screens/deeplink/DeepLink.tsx
> +                onPress={() => Linking.openURL(createdLink)}
Githubのアプリだとうまくいきますね

2021-08-02 05:30 UTC, tani-takanori commented on DynamicLinksSandbox/src/screens/deeplink/DeepLink.tsx
> +                onPress={() => Linking.openURL(createdLink)}
これURLかどうかわからんのか

2021-08-02 06:00 UTC, tani-takanori commented on DynamicLinksSandbox/src/screens/deeplink/DeepLink.tsx
> +                onPress={() => Linking.openURL(createdLink)}
https://ws4020reactnativesandbox.page.link/YYbv6KYPMjNKdPUA8

2021-08-02 06:42 UTC, tani-takanori commented on DynamicLinksSandbox/src/screens/deeplink/DeepLink.tsx
> +                onPress={() => Linking.openURL(createdLink)}
Liking.openURLじゃなくてLinking.emit('url')に変更してListnerの処理も変えました。
https://github.com/ws-4020/react-native-sandbox/pull/1/commits/75adbf6790acfe0c4a806c7e2c9c6211b4950515

2021-08-02 07:03 UTC, creature-water-valley commented on DynamicLinksSandbox/src/screens/deeplink/DeepLink.tsx
> +                onPress={() => Linking.openURL(createdLink)}
Linking.emitってドキュメント上にはないんですね。
https://reactnative.dev/docs/0.63/linking#methods

2021-08-02 07:13 UTC, creature-water-valley commented on DeepLink/README.md
> + - 自分たちでCustomドメインを取得し、最初にアクセスしたときにサーバ側で端末と紐付けて情報を保持する。
これって、端末情報って送られてくるんですか？？

2021-08-02 07:17 UTC, tani-takanori commented on DeepLink/README.md
> + - 自分たちでCustomドメインを取得し、最初にアクセスしたときにサーバ側で端末と紐付けて情報を保持する。
端末情報を送るように作り込まないといけないです。

さらっと書いちゃったけど、作り込みだいぶしないと実現できないってわからないな

2021-08-02 07:19 UTC, creature-water-valley commented on DeepLink/README.md
> + - 自分たちでCustomドメインを取得し、最初にアクセスしたときにサーバ側で端末と紐付けて情報を保持する。
いや、僕が誤解してるのかも。
最初にアクセスってどこからのアクセスですか？

2021-08-02 07:22 UTC, tani-takanori commented on DeepLink/README.md
> + - 自分たちでCustomドメインを取得し、最初にアクセスしたときにサーバ側で端末と紐付けて情報を保持する。
> どこからのアクセス

モバイル端末のブラウザです。

2021-08-02 07:47 UTC, tani-takanori commented on DeepLink/README.md
> + - 自分たちでCustomドメインを取得し、最初にアクセスしたときにサーバ側で端末と紐付けて情報を保持する。
制限とします

2021-08-02 07:53 UTC, creature-water-valley commented on DeepLink/README.md
> +このとき、ユーザは最新のURLをアプリで受け取る必要があるが、古い（1回目）URLを取得する無効なURLを受けとってしまう。
末尾の文章がちょっとおかしい気がします。

2021-08-02 08:30 UTC, tani-takanori commented on DeepLink/README.md
> +このとき、ユーザは最新のURLをアプリで受け取る必要があるが、古い（1回目）URLを取得する無効なURLを受けとってしまう。
修正しました
https://github.com/ws-4020/react-native-sandbox/pull/1/commits/59c2983ad1f3dd648cc88f410e4fbbf143ba0df4

2021-08-02 08:44 UTC, in-a-paddy commented on DeepLink/README.md
> + - 自分たちでCustomドメインを取得し、最初にアクセスしたときにサーバ側で端末と紐付けて情報を保持する。
パラメータの渡し方（Universal Link or Clipboard）とアプリ状態・起動方法（初回起動・アプリアイコンタップ、初回起動・Linkタップ etc.）で、どこからURLを取得するのか整理しておいた方が良さそう。Clipboardの仕様がiOS/Androidで違うから、それぞれのOSで確認したほうが良さそう。

あと、特殊なケースとしてDynamic Linkタップ→コピー→アプリインストール→別のテキストをコピー→アイコンタップでどうなるの？ってのも気になる。ウェブアプリからはGlobal Pasteboardにしか入れられないんじゃないかと思うから、引き継ぐの無理そうな気がするんだけど、、、

2021-08-02 08:52 UTC, tani-takanori commented on DeepLink/README.md
> + - 自分たちでCustomドメインを取得し、最初にアクセスしたときにサーバ側で端末と紐付けて情報を保持する。
iOSの整理
https://github.com/ws-4020/react-native-sandbox/pull/1/commits/e685be4901786907161b96ee38e2b14e5f1e76f3

Androidか…
EmulatorにDeploy Gateいれて確認します

特殊なケースパターンはiOSではイケてるので追記します。

2021-08-02 08:53 UTC, in-a-paddy commented on DeepLink/README.md
> +|No|アプリ起動|起動回数|クリップボード|利用されるデータ|
クリップボードにデータありなし、と無効なデータ（特にディープリンクに関係ない文字列）の場合も情報がほしいかな。

2021-08-02 09:53 UTC, in-a-paddy commented on DeepLink/README.md
> + - 自分たちでCustomドメインを取得し、最初にアクセスしたときにサーバ側で端末と紐付けて情報を保持する。
Androidはクリップボード経由しないけど、フロー違うから確認しておいたほうがいいのかな？

2021-08-06 02:31 UTC, creature-water-valley commented on DeepLink/README.md
> + - 自分たちでCustomドメインを取得し、最初にアクセスしたときにサーバ側で端末と紐付けて情報を保持する。
この表にmatchTypeも追加されるんですかね？

2021-08-19 08:07 UTC, tani-takanori commented on DeepLink/README.md
> + - 自分たちでCustomドメインを取得し、最初にアクセスしたときにサーバ側で端末と紐付けて情報を保持する。
65439edbde090686715433ba4ca0ac7042a7b229
bca1732133dd1d251bdcbc02c242c5a638c9c407

2021-08-19 08:07 UTC, tani-takanori commented on DeepLink/README.md
> +|No|アプリ起動|起動回数|クリップボード|利用されるデータ|
65439edbde090686715433ba4ca0ac7042a7b229
bca1732133dd1d251bdcbc02c242c5a638c9c407

2021-08-19 08:08 UTC, tani-takanori commented on DeepLink/README.md
> + - 自分たちでCustomドメインを取得し、最初にアクセスしたときにサーバ側で端末と紐付けて情報を保持する。
> Androidはクリップボード経由しないけど、フロー違うから確認しておいたほうがいいのかな？

うーん...page.linkで取得されるURLがどうなってるかは確認しておくけど、OSレベルでURL保存してくれてそうだしなぁ

2021-08-19 09:08 UTC, tani-takanori commented
> ↓の時に、どのリスナ（getInitialLink / onLink）で取れるか、もしくは取れないかの情報もあるとわかりやすいなって思いました。
> 
> * Cold Start
> * バックグラウンド
> * フォアグラウンド

https://github.com/ws-4020/react-native-sandbox/pull/1/commits/e2114bb75dd0e806ddab32eec5e197b4de2c8e16
 対応しました

2021-08-20 04:20 UTC, tani-takanori commented on DeepLink/README.md
> + - 自分たちでCustomドメインを取得し、最初にアクセスしたときにサーバ側で端末と紐付けて情報を保持する。
iOSの場合だけLinkingを利用するように修正した
https://github.com/ws-4020/react-native-sandbox/pull/1/commits/a4f12296032f5307c069224222990f52d6671ab1

2021-08-23 04:38 UTC, creature-water-valley commented on DeepLink/README.md
> +|No|アプリ起動|起動回数|クリップボード|iOS利用されるデータ|matchType|
一番最後のヘッダカラムがないような？

2021-08-23 04:44 UTC, creature-water-valley commented on DeepLink/README.md
> +|1|リンクをタップ|0|展開URL|リンク|unique|initialLink|
前提として、アプリがインストール済みの場合ですかね？

2021-08-23 04:46 UTC, creature-water-valley commented on DeepLink/README.md
> +|13|アプリアイコンをタップ|1以上|展開URL|-|-|
最後のカラムが足りてない？

2021-08-23 04:47 UTC, creature-water-valley commented on DeepLink/README.md
> +`page.link`URLは下記表以外のどういう条件で利用されるか（いつまで有効かなど）の調査はしていませんが、デバイスのIP（Wifi接続への変更）で無効になることは確認しています。
```suggestion
`page.link`URLは下記表以外のどういう条件で利用されるか（いつまで有効かなど）の調査はしていませんが、デバイスのIP変更（Wifi接続への変更）で無効になることは確認しています。
```

2021-08-23 04:56 UTC, creature-water-valley commented on DeepLink/README.md
> +|1|リンクをタップ|0|展開URL|リンク|unique|initialLink|
その場合、アプリが未インストールのパターンも表にほしいです。

2021-08-23 04:57 UTC, creature-water-valley commented on DeepLink/README.md
> +|5|リンクをタップ|1以上|正規URL|リンク|unique|initialLink|
どこかに記載してあったらすいません。これってCold Startが前提になってます？？

2021-08-23 05:08 UTC, tani-takanori commented on DeepLink/README.md
> +|1|リンクをタップ|0|展開URL|リンク|unique|initialLink|
アプリ起動がどのパターンに当たるかがわかりづらそうなので、表の前にどのパターンに当たるか記載してみます。
※アプリが未インストールの場合、"通常"はクリップボードに展開URLがある状態でアプリアイコンタップのパターンが該当します。

2021-08-23 05:13 UTC, creature-water-valley commented on DeepLink/README.md
> +|11|アプリアイコンをタップ|0|その他データ|`page.link`URL|week|onLink|
matchTypeが2（default）が返ってきたんですが、手順違いますかね？

* アプリをアンインストール
* アプリをインストール
* なんか適当なものをコピー
* アプリアイコンタップ

2021-08-23 05:15 UTC, tani-takanori commented on DeepLink/README.md
> +|11|アプリアイコンをタップ|0|その他データ|`page.link`URL|week|onLink|
？？
link表示されました？？

2021-08-23 05:24 UTC, creature-water-valley commented on DeepLink/README.md
> +|11|アプリアイコンをタップ|0|その他データ|`page.link`URL|week|onLink|
1.17ですね

2021-08-23 05:27 UTC, tani-takanori commented on DeepLink/README.md
> +|5|リンクをタップ|1以上|正規URL|リンク|unique|initialLink|
すいません。Cold Startが前提になってます...
たしかに1以上だとBackgroundなら onLinkですね...

2021-08-23 06:46 UTC, tani-takanori commented on DeepLink/README.md
> +|11|アプリアイコンをタップ|0|その他データ|`page.link`URL|week|onLink|
再現しないです...
水谷さんの環境だと再現するっぽいので week or default(not unique)にしておきます

2021-08-23 07:18 UTC, in-a-paddy requested changes

2021-08-23 07:18 UTC, in-a-paddy commented on DeepLink/README.md
> +未インストール状態で`OPEN`ボタンを押したときのURLを"`page.link`URL"と表記しています。
何が違うんだっけ？
* 展開URL
* 正規URL
* ShortURL
* リンク
* `page.link`URL

どのケースであっても、クリップボードに入っているものがそのまま使われるわけじゃないっぽいことはわかるんだけど、説明ないから理解するの厳しいのでは。

2021-08-23 07:18 UTC, in-a-paddy commented on DeepLink/README.md
> +## ユースケース
この項は何が説明したいんだっけ？

2021-08-23 07:18 UTC, in-a-paddy commented on DeepLink/README.md
> +## 未インストールのStep
これはテスト方法？？

2021-08-23 07:18 UTC, in-a-paddy commented on DeepLink/README.md
> +## ユースケース
全体的にREADME.mdで何を説明したいのかが受け取りにくい感じがする。

2021-08-23 07:54 UTC, tani-takanori commented on DeepLink/README.md
> +|13|アプリアイコンをタップ|1以上|展開URL|-|-|
https://github.com/ws-4020/react-native-sandbox/pull/1/commits/dd8d0d0be97d10d6db54a6bdccbf049392e687d4

2021-08-23 07:54 UTC, tani-takanori commented on DeepLink/README.md
> +|1|リンクをタップ|0|展開URL|リンク|unique|initialLink|
https://github.com/ws-4020/react-native-sandbox/pull/1/commits/dd8d0d0be97d10d6db54a6bdccbf049392e687d4

2021-08-23 07:54 UTC, tani-takanori commented on DeepLink/README.md
> +|No|アプリ起動|起動回数|クリップボード|iOS利用されるデータ|matchType|
https://github.com/ws-4020/react-native-sandbox/pull/1/commits/dd8d0d0be97d10d6db54a6bdccbf049392e687d4

2021-08-23 07:54 UTC, tani-takanori commented on DeepLink/README.md
> +|5|リンクをタップ|1以上|正規URL|リンク|unique|initialLink|
https://github.com/ws-4020/react-native-sandbox/pull/1/commits/dd8d0d0be97d10d6db54a6bdccbf049392e687d4

2021-08-23 07:55 UTC, tani-takanori commented on DeepLink/README.md
> +|11|アプリアイコンをタップ|0|その他データ|`page.link`URL|week|onLink|
`none`もあり得るので `not unique`にしました
https://github.com/ws-4020/react-native-sandbox/pull/1/commits/dd8d0d0be97d10d6db54a6bdccbf049392e687d4

2021-08-23 07:56 UTC, tani-takanori commented on DeepLink/README.md
> +未インストール状態で`OPEN`ボタンを押したときのURLを"`page.link`URL"と表記しています。
説明追加
https://github.com/ws-4020/react-native-sandbox/pull/1/commits/c5292af5c678ab0ac864197e244d2f9d436f4490

2021-08-23 07:56 UTC, tani-takanori commented on DeepLink/README.md
> +## ユースケース
作業経過のメモとかがバラバラと残っているので全体的に見直し

2021-08-23 07:57 UTC, tani-takanori commented on DeepLink/README.md
> +## 未インストールのStep
公開していない場合の検証方法です。ちょっと修正しました。

https://github.com/ws-4020/react-native-sandbox/pull/1/commits/4270861787233d35e1e0bf1fd714cdae3c957a63

2021-08-23 08:04 UTC, in-a-paddy commented on DeepLink/README.md
> +|11|アプリアイコンをタップ|0|その他データ|`page.link`URL|week|onLink|
week -> weak かな

2021-08-23 08:43 UTC, creature-water-valley commented on DeepLink/README.md
> +「ドメインの関連付け」を利用しないでもアプリケーションの起動はGoogleService-Info.plistのbundleIdと比較していないので個人開発者アカウントでURLの作成可能である。
```suggestion
「ドメインの関連付け」を利用しないでもアプリケーションの起動はGoogleService-Info.plistのbundleIdと比較していないので個人開発者アカウントでURLの作成が可能です。
```

2021-08-23 08:43 UTC, creature-water-valley commented on DeepLink/README.md
> +開発用のGoogleService-Info.plistとgoogle-service.jsonを作成しSDKを設定してから開発者に配布すればよい。
```suggestion
開発用のGoogleService-Info.plistとgoogle-service.jsonを作成しSDKを設定してから開発者に配布してください。
```

2021-08-23 08:45 UTC, creature-water-valley commented on DeepLink/README.md
> +開発用のGoogleService-Info.plistとgoogle-service.jsonを作成しSDKを設定してから開発者に配布すればよい。
ですます調に変えたけど、むしろですます調じゃない方がこのページは多そう。。。
全体的に、どっちかに寄せてもらいたいです。

2021-08-23 09:51 UTC, tani-takanori commented on DeepLink/README.md
> +開発用のGoogleService-Info.plistとgoogle-service.jsonを作成しSDKを設定してから開発者に配布すればよい。
https://github.com/ws-4020/react-native-sandbox/pull/1/commits/551df7b316845269be723f53548b380b1d2e997b

2021-08-24 05:48 UTC, in-a-paddy requested changes

2021-08-24 05:48 UTC, in-a-paddy commented on DeepLink/README.md
> +
この行はいらないと思う。

```suggestion
```

2021-08-24 05:48 UTC, in-a-paddy commented on DeepLink/README.md
> +GoogleService-Info.plistをDownloadして設定します。
これ、Xcode上の作業はFirebaseの場合は必要ないんだっけ？

2021-08-24 05:48 UTC, in-a-paddy commented on DeepLink/README.md
> +Customドメイン（たとえば`sandbox.ws-4020.mobile-app.com`など）も利用可能ですが、`page.link`でユースケースを満たせているため検証していません。
```suggestion
カスタムドメイン（たとえば`sandbox.ws-4020.mobile-app.com`など）も利用可能ですが、`page.link`でユースケースを満たせているため検証していません。
```

2021-08-24 05:48 UTC, in-a-paddy commented on DeepLink/README.md
> +GoogleService-Info.plistをDownloadして設定します。
Androidではどこに配置するか書いてあるので、iOSについても書いておいたら？と思ってしまった。

2021-08-24 05:48 UTC, in-a-paddy commented on DeepLink/README.md
> +|アプリの状態|取得するリスナー|備考|
リスナーとは限らないような

2021-08-24 05:48 UTC, in-a-paddy commented on DeepLink/README.md
> +|フォアグラウンド|Context.setURL|Linking.openではブラウザが開くためUXの点から採用しません。Linking.emitはfirebaseの内部実装（キー）に依存するため採用しません。|
`Context.setURL`ってなんのこと？？

2021-08-24 05:48 UTC, in-a-paddy commented on DeepLink/README.md
> +下記表は未インストール状態でURLを開き、`preview.page.link`のWebページで`OPEN`ボタンを押した状態で検証しています。
「下記表は未インストール状態でURLを開き」ってあるけど、未インストールじゃないものも含まれてると思う。

2021-08-24 05:48 UTC, in-a-paddy commented on DeepLink/README.md
> +|9|アプリアイコンをタップ|0|展開URL|クリップボード|unique|onLink|
「起動時のリンク」「クリップボード」「`page.link`URL」って直交するもの？クリップボードに展開URLが入っていて、リンクをタップしたときにはクリップボードではないんだっけ？

2021-08-24 05:48 UTC, in-a-paddy commented on DeepLink/README.md
> +`page.link`URLは下記表以外のどういう条件で利用されるか（いつまで有効かなど）の調査はしていませんが、デバイスのIP変更（Wifi接続への変更）で無効になることは確認しています。
「未インストール状態で`OPEN`ボタンを押したときのURLを"`page.link`URL"と表記しています。」ってのがよくわかんないからかもしれないけど、`page.link`URLってのはブラウザのアドレスバーに表示されているURLではない？
なんか、どういうタイミングでどのURLが登場するのかわかってないと、読めない気がする

2021-08-24 05:48 UTC, in-a-paddy commented on DeepLink/README.md
> +|1|リンクをタップ|0|展開URL|起動時のリンク|unique|initialLink|
こっちでは`onLink`は呼ばれない？

2021-08-24 05:48 UTC, in-a-paddy commented on DeepLink/README.md
> +リトライしてもらうことはユーザに大きな負担をかけないため、許容します。
突然リトライの話が出てきてよくわからない。`matchType`が`unique`のURLを取得できないから、もう一度リンクを開いて貰う必要があるってことではない？

`page.link`は「未インストール状態で`OPEN`ボタンを押したときのURLを"`page.link`URL"」って定義だから、なんでこのURLを取得できたときはリトライが必要なのか理解できないと思う。

2021-08-24 05:48 UTC, in-a-paddy commented on DeepLink/README.md
> +「ドメインの関連付け」を利用しないでもアプリケーションの起動はGoogleService-Info.plistのbundleIdと比較していないので個人開発者アカウントでURLの作成が可能です。
こういう意味なんだっけ？

```suggestion
「ドメインの関連付け」にはADPかADEPが必要なので、実際にリンクからアプリケーションを起動するテストをするには、ADPかADEPでビルドしたアプリケーションが必要です。

ただし、個人開発者アカウントでビルドした場合でもアプリケーションの起動はできるので、リンクからアプリケーションを起動するユースケースを含まない部分であれば、個人開発者アカウントで開発できます。
```

2021-08-24 05:48 UTC, in-a-paddy commented on DeepLink/README.md
> +開発用のGoogleService-Info.plistとgoogle-service.jsonを作成しSDKを設定してから開発者に配布してください。
ここもよくわからんけど、こういうこと？
```suggestion
そのため、開発用のGoogleService-Info.plistとgoogle-service.jsonを作成しSDKを設定してから開発者に配布しても、開発者全員に配布用証明書を提供する必要はありません。
```

2021-08-24 05:48 UTC, in-a-paddy commented on DeepLink/README.md
> +そのため、Google Playの内部テスト版での検証などもできていないません。
これって、内部テスト版だから公開しなくても検証できるような、、、？

2021-08-24 05:48 UTC, in-a-paddy commented on DeepLink/README.md
> +ただし、アプリのリンク作成時に `fallbackUrl` を設定するためビルドバリアントで切り替えるようにすれば対応できる想定です。
こういう意味で合ってる？

```suggestion
ストアに誘導する場合は、アプリ内でDynamic Linkを作成する時に指定する `fallbackUrl` にストアのURLを設定することで対応できる想定です。ビルドバリアントでこの`fallbackUrl`を切り替えることで、本番リリース用ビルドバリアントでビルドされたアプリではストアに誘導し、他環境では異なるURLに誘導するように設定できます。
```

2021-08-24 05:48 UTC, in-a-paddy commented on DeepLink/README.md
> +本来はユーザがWebサイトにアクセスするか、アプリで起動するかを選択できます。
「本来」ってどういうことだっけ？

2021-08-24 05:48 UTC, in-a-paddy commented on DeepLink/README.md
> +#### Androidアプリを複数作成
何に問題があって、なんのために確認する必要があるんだ？ってのがわからんです、、、

2021-08-24 06:00 UTC, tani-takanori commented on DeepLink/README.md
> +#### Androidアプリを複数作成
鍵を複数利用する場合にWebサイト１つでできるかどうかです。

https://developer.android.google.cn/training/app-links/verify-site-associations?hl=ja#multiple-apps

できない場合はManifestの設定いれないとイケないかなって思ってます
https://developer.android.google.cn/training/app-links/verify-site-associations?hl=ja#multi-host

2021-08-24 06:45 UTC, creature-water-valley commented on DeepLink/README.md
> +No10ではShortLinkをクリップボードから取得する（iOS14以降の通知がでる）が利用せずに`page.link`を利用します。
```suggestion
No10ではShortURLをクリップボードから取得する（iOS14以降の通知がでる）が利用せずに`page.link`を利用します。
```

2021-08-24 07:18 UTC, tani-takanori commented on DeepLink/README.md
> +GoogleService-Info.plistをDownloadして設定します。
https://github.com/ws-4020/react-native-sandbox/pull/1/commits/f515e9ee22ab37ac7e9c3e34056a1404809a314c

2021-08-24 07:20 UTC, tani-takanori commented on DeepLink/README.md
> +そのため、Google Playの内部テスト版での検証などもできていないません。
62f1fdeb9d168f1e1367b1a4dd6a99e39ebea074

2021-08-24 08:23 UTC, tani-takanori commented on DeepLink/README.md
> +|9|アプリアイコンをタップ|0|展開URL|クリップボード|unique|onLink|
リンクをタップしたときはタップしたリンクですね。
リンクをタップして、インストールしたあとに起動した場合はクリップボードです。

2021-08-24 09:28 UTC, tani-takanori commented on DeepLink/README.md
> +|アプリの状態|取得するリスナー|備考|
https://github.com/ws-4020/react-native-sandbox/pull/1/commits/9eb7d2da3c8944901d16f0bd13979b212859f3d2

2021-08-24 10:03 UTC, tani-takanori commented on DeepLink/README.md
> +下記表は未インストール状態でURLを開き、`preview.page.link`のWebページで`OPEN`ボタンを押した状態で検証しています。
あーちょっと分かりづらいので修正します。

実施するときに 「`preview.page.link`のWebページ上で`OPEN`ボタンを押している端末」で実施しているということを表現しようとしていました。

2021-08-24 10:27 UTC, tani-takanori commented on DeepLink/README.md
> +下記表は未インストール状態でURLを開き、`preview.page.link`のWebページで`OPEN`ボタンを押した状態で検証しています。
875789a75f251c2553182c462e5679ac92143271

2021-08-24 10:29 UTC, tani-takanori commented on DeepLink/README.md
> +`page.link`URLは下記表以外のどういう条件で利用されるか（いつまで有効かなど）の調査はしていませんが、デバイスのIP変更（Wifi接続への変更）で無効になることは確認しています。
OPENボタン押したときにクリップボードにコピーされたやつが端末外（おそらくFirebase）に保存されて、その保存されたURLです。
ちょっと書き方変えました

875789a75f251c2553182c462e5679ac92143271

2021-08-24 10:29 UTC, tani-takanori commented on DeepLink/README.md
> +|1|リンクをタップ|0|展開URL|起動時のリンク|unique|initialLink|
インストール済みで起動していない場合は呼ばれなかったです

2021-08-24 10:31 UTC, tani-takanori commented on DeepLink/README.md
> +リトライしてもらうことはユーザに大きな負担をかけないため、許容します。
ごめんなさい！もともと挙動とiOSのバグに気づいていないときに書いていた内容を消せていませんでした。

875789a75f251c2553182c462e5679ac92143271

※ iOSはLinking.getInitialURLを利用することで発生しなくなってます

2021-08-24 10:37 UTC, tani-takanori commented on DeepLink/README.md
> +本来はユーザがWebサイトにアクセスするか、アプリで起動するかを選択できます。
> 本来
https:なのでブラウザからのアクセスですよ。ということでした。
page.linkの場合はブラウザでアクセスされてもインストールを促しますが、OS機能の場合はWebサイトへのアクセスがあります。

875789a75f251c2553182c462e5679ac92143271

2021-08-25 02:01 UTC, creature-water-valley commented on DeepLink/README.md
> + - QRコードを読み取ってアプリを起動：URLからアプリを起動する方法
この検証アプリってQRコードは生成してないような

2021-08-25 02:07 UTC, creature-water-valley commented on DeepLink/README.md
> +|Cold Start| firebase.getInitialLink| firebase.getInitialLinkには[issue](https://github.com/invertase/react-native-firebase/issues/2660)があるためLinking.getInitialURLをresolveします|
利用するメソッドって、iOSの場合は`Linking.getInitialURL`で、Androidの場合が`firebase.getInitialLink`じゃないんでしたっけ？

2021-08-25 02:08 UTC, creature-water-valley commented on DeepLink/src/context/DeepLinkContext.tsx
> +  const getInitailLink = useCallback(() => {
`getInitailLink`→`getInitialLink`

2021-08-25 02:14 UTC, creature-water-valley commented on DeepLink/README.md
> +詳しくは[オペレーティングシステムを統合する](https://firebase.google.com/docs/dynamic-links/operating-system-integrations)のiOSフローチャートを参照してください。
Androidの場合は、Androidのフローチャートを参照でいい気がしました

```suggestion
詳しくは[オペレーティングシステムを統合する](https://firebase.google.com/docs/dynamic-links/operating-system-integrations)のフローチャートを参照してください。
```

2021-08-25 02:17 UTC, tani-takanori commented on DeepLink/README.md
> + - QRコードを読み取ってアプリを起動：URLからアプリを起動する方法
たしかに...

2021-08-25 02:20 UTC, tani-takanori commented on DeepLink/README.md
> + - QRコードを読み取ってアプリを起動：URLからアプリを起動する方法
https://github.com/ws-4020/mobile-app-crib-notes/pull/374

2021-08-25 02:22 UTC, tani-takanori commented on DeepLink/README.md
> +|Cold Start| firebase.getInitialLink| firebase.getInitialLinkには[issue](https://github.com/invertase/react-native-firebase/issues/2660)があるためLinking.getInitialURLをresolveします|
issueがあるので、`Linking.getInitialURL` つかうって感じにしてました。※本来はfirebase.getInitialLink使う

OS毎に分けて書いた上で備考になんで分けてるか書いておいたほうがいいですかね？

2021-08-25 02:25 UTC, creature-water-valley commented on DeepLink/README.md
> +Deploy Gateでの検証をしていますが、Google Playの内部テスト版での検証などもできていないません。
```suggestion
Deploy Gateでの検証をしていますが、Google Playの内部テスト版での検証などもできていません。
```

2021-08-25 02:29 UTC, tani-takanori commented on DeepLink/src/context/DeepLinkContext.tsx
> +  const getInitailLink = useCallback(() => {
e504e264d38cf1e45fe9023589b33a1360b591c9

2021-08-25 02:35 UTC, creature-water-valley commented on DeepLink/README.md
> +## 検証アプリの環境構築
このREADMEの最初の方にあった環境構築と、ここの環境構築は何が違うんですかね？

2021-08-25 02:37 UTC, creature-water-valley commented on DeepLink/README.md
> +|Cold Start| firebase.getInitialLink| firebase.getInitialLinkには[issue](https://github.com/invertase/react-native-firebase/issues/2660)があるためLinking.getInitialURLをresolveします|
> OS毎に分けて書いた上で備考になんで分けてるか書いておいたほうがいいですかね？

ですね、そっちの方がわかりやすいと思いますー

2021-08-25 02:38 UTC, creature-water-valley commented on DeepLink/src/context/DeepLinkContext.tsx
> +  const getInitailLink = useCallback(() => {
多分、修正はこっち

3a326e164c5808e0f60aa2935566be30c51167c0

2021-08-25 02:40 UTC, tani-takanori commented on DeepLink/README.md
> +## 検証アプリの環境構築
ErrorHandlingと構成合わせたときに内容が重複してしまいました

6e44ac027419a8e9b689dfd7ad7682b73a47ca7c

2021-08-25 02:52 UTC, tani-takanori commented on DeepLink/README.md
> +|Cold Start| firebase.getInitialLink| firebase.getInitialLinkには[issue](https://github.com/invertase/react-native-firebase/issues/2660)があるためLinking.getInitialURLをresolveします|
6e44ac027419a8e9b689dfd7ad7682b73a47ca7c

2021-08-25 02:52 UTC, tani-takanori commented on DeepLink/src/context/DeepLinkContext.tsx
> +  const getInitailLink = useCallback(() => {
ごめんなさい..

2021-08-25 07:30 UTC, in-a-paddy commented on DeepLink/README.md
> +GoogleService-Info.plistをDownloadして設定します。
> Xcodeを起動し、File > Add New File to DeepLinkで配置した`GoogleService-Info.plist`を選択します。

あ、ここは書かなくていいのか。リポジトリをクローンした人はファイル置くだけだよね？

2021-08-25 07:41 UTC, in-a-paddy commented on DeepLink/README.md
> +アプリからURLを作成しないケースなので利用しないが、アプリ外で作成する場合に使用すると想定されます。
```suggestion
言語向けのSDKが提供されていないなどの理由でFirebase Dynamic LinkのSDKを利用できない場合には、REST APIを使用してURLを作成します。
```

2021-08-25 07:41 UTC, in-a-paddy commented on DeepLink/README.md
> +- Firebase Console上で作成する
こっちだよね？

```suggestion
### Firebase Console上で作成する
```

2021-08-25 07:41 UTC, in-a-paddy commented on DeepLink/README.md
> +未公開アプリを使ってディープリンクを利用する方法を検証します。
```suggestion
ストアに公開していない開発中のアプリを使ってディープリンクを利用する方法を検証します。
```

2021-08-25 07:41 UTC, in-a-paddy commented on DeepLink/README.md
> +  1. TestFlightからアプリをインストール
```suggestion
  1. TestFlightからアプリをインストール
  1. アプリを起動
```

2021-08-25 07:41 UTC, in-a-paddy commented on DeepLink/README.md
> + 1. アプリを起動
```suggestion
 1. アプリを起動
 1. URLを取得
```

2021-08-25 07:45 UTC, tani-takanori commented on DeepLink/README.md
> +- Firebase Console上で作成する
こっちです！！

2021-08-25 08:56 UTC, creature-water-valley commented on DeepLink/README.md
> +|Cold Start| firebase.getInitialLink| firebase.getInitialLinkには[issue](https://github.com/invertase/react-native-firebase/issues/2660)があるためLinking.getInitialURLをresolveします|
おそらくこっち
fcfea418de0fcdb306c5a5a30d11cb5582a22090

2021-08-25 09:01 UTC, creature-water-valley approved these changes, later dismissed

2021-08-25 09:02 UTC, tani-takanori commented on DeepLink/README.md
> +|Cold Start| firebase.getInitialLink| firebase.getInitialLinkには[issue](https://github.com/invertase/react-native-firebase/issues/2660)があるためLinking.getInitialURLをresolveします|
すいません。
`Copy the full SHA` をクリックしたときにエラーが出ていてコピーできていないみたいなので、これからはちゃんとハッシュのURLをコピーします...

2021-08-26 06:34 UTC, tani-takanori reviewed
メモ

2021-08-26 06:34 UTC, tani-takanori commented on DeepLink/README.md
> +### ドメインとアプリの紐付け
Firebaseでのプロジェクトの作成〜page.linkドメインの作成までのページのリンクでいい。

2021-08-26 06:34 UTC, tani-takanori commented on DeepLink/README.md
> +紐付けに必要なリソースを配置してビルドします。
Firebaseの設定方法にガイドする

2021-08-26 06:34 UTC, tani-takanori commented on DeepLink/README.md
> +- アプリが作成したURLを共有して、起動したアプリに情報を渡す。
アプリでできることを書く。＆Navigationもしていないことも

2021-08-27 01:39 UTC, creature-water-valley commented on DeepLink/README.md
> +Dynamic Linksを利用して「ディープリンクのURLの作成」と「URLからアプリを起動する方法」を検証します。
「Dynamic LinksのURLをアプリで取得する方法」も検証しているのでは？と思いました

2021-08-27 01:43 UTC, creature-water-valley commented on DeepLink/README.md
> +- 新しいドメインを紐付ける場合はXcodeを起動し、CapabillitiesのAssociated Domainsに`applinks:...`を設定してください。
Androidの場合と、同様に↓とかのリンクを付けてあげた方が親切かなって思いました。

https://firebase.google.com/docs/dynamic-links/ios/receive?hl=ja

2021-08-27 01:55 UTC, creature-water-valley commented on DeepLink/README.md
> +|No|アプリ起動|起動回数|クリップボード|iOS利用されるデータ|matchType|event|
「iOS利用されるデータ」っていうのが分かりづらいのかなって思いました。これは、「アプリで受け取るデータ」と同意ですよね？

2021-08-27 01:56 UTC, creature-water-valley commented on DeepLink/README.md
> +|No|アプリ起動|起動回数|クリップボード|iOS利用されるデータ|matchType|event|
後、急にmatchTypeが出てきた気がします。。。ちょっとなんのこと？ってなりそうな。

2021-08-27 02:26 UTC, tani-takanori commented on DeepLink/README.md
> +Dynamic Linksを利用して「ディープリンクのURLの作成」と「URLからアプリを起動する方法」を検証します。
検証しているので追加しました

f49602789eb25556d9cb154759ade0021f113d37

2021-08-27 02:41 UTC, tani-takanori commented on DeepLink/README.md
> +- 新しいドメインを紐付ける場合はXcodeを起動し、CapabillitiesのAssociated Domainsに`applinks:...`を設定してください。
4d9733b6954fb554263ad6fef86a3664f79c1735

2021-08-27 02:42 UTC, tani-takanori commented on DeepLink/README.md
> +|No|アプリ起動|起動回数|クリップボード|iOS利用されるデータ|matchType|event|
> 「iOS利用されるデータ」っていうのが分かりづらいのかなって思いました。これは、「アプリで受け取るデータ」と同意ですよね？

アプリで受け取るデータのほうが適切なので修正しました。


Tableのヘッダをリンクするだけだと`unique`と`not unique`にした理由が分かりづらいかなとおもい説明追加しました。

154ea1c794e2b9e3286798dd0916b5a0c154208e

2021-08-27 05:01 UTC, creature-water-valley commented on DeepLink/README.md
> +|No|アプリ起動|起動回数|クリップボード|iOS利用されるデータ|matchType|event|
説明かテーブルのヘッダ、もしくは両方にmatchType(iOS)って感じで、iOSのみっていうのがわかるような記載にした方がいいかなって思いました。

2021-08-27 05:20 UTC, tani-takanori commented on DeepLink/README.md
> +|No|アプリ起動|起動回数|クリップボード|iOS利用されるデータ|matchType|event|
両方につけちゃいます！

b90d1d3a882d0a283ab6b5f6edc36750df731ae5

2021-08-27 05:53 UTC, creature-water-valley approved these changes

2021-08-27 10:28 UTC, ghost commented on DeepLink/README.md
> +#### Androidアプリを複数作成
~~これはREADME.mdになくてもいいんじゃないかな、と思った。~~

検証していない項目としては残しておいたほうがいいのか。

2021-08-27 10:47 UTC, tani-takanori commented on DeepLink/README.md
> +#### Androidアプリを複数作成
https://github.com/ws-4020/react-native-sandbox/pull/1/commits/2f8769f71b7172721370261c7ea85321cdbe317f

2021-08-30 08:38 UTC, in-a-paddy commented on DeepLink/README.md
> +そのため、debug用やテスト用、本番用など複数のkeystoreが利用できることを確認する必要があります。
何を確認しないといけないんだっけ？？こういうことでいい？
```suggestion
そのため、一つのドメインをdebug用やテスト用、本番用などの複数のkeystoreやアプリケーションIDに関連付ける必要があるはずですが、まだその構成ではテストできていません。
```

2021-09-06 09:34 UTC, ghost commented on DeepLink/README.md
> +動作確認をする場合、ディープリンクを利用できる`debug.keystore`ではないので、Firebaseのアプリに登録しているフィンガープリントが一致するkeystoreを利用してください。
```suggestion
初期設定してある`debug.keystore`のフィンガープリントはFirebaseアプリには登録していないので、ディープリンクの動作確認のためには、署名に利用するkeystoreを変更しなくてはいけない点に注意してください。
```

2021-09-06 09:34 UTC, ghost commented on DeepLink/README.md
> +ユーザがURLをタップしたときにURLを取得するには「アプリの状態」毎に次の通りに実装しています。
```suggestion
ディープリンクからアプリを起動した場合、起動元のURLを取得するように実装しています。ディープリンクをタップする前のアプリの状態によって、URLを取得できるメソッドは以下のように異なっています。
```

2021-09-06 09:34 UTC, in-a-paddy commented on DeepLink/README.md
> +フォアグラウンドではディープリンクの機能を利用せず、アプリ内で処理します。そのときDynamic Linksの中に含まれるlinkを取得するためにresolveを利用します。
ごめん、わからん。Linking.openとかLinking.emitってなんのことを指してるの？ブラウザが開く云々ってのはディープリンクを開く側の話であって、受け取る側の話ではないのでは、、、

2021-09-06 10:26 UTC, tani-takanori commented on DeepLink/README.md
> +フォアグラウンドではディープリンクの機能を利用せず、アプリ内で処理します。そのときDynamic Linksの中に含まれるlinkを取得するためにresolveを利用します。
アプリがフォアグラウンドの時にLinking（Universal LinksとかApp Links）経由で`firebase.onLink`を利用しようとするとうまくいかないから、アプリが作成したディープリンクURLをアプリ内で処理するときは`firebase.resolveLink`を利用するってことを書きたかったです

2021-09-06 11:22 UTC, tani-takanori commented on DeepLink/README.md
> +フォアグラウンドではディープリンクの機能を利用せず、アプリ内で処理します。そのときDynamic Linksの中に含まれるlinkを取得するためにresolveを利用します。
2d95f94ca900252c553fb6ee691b3485eb7e5083

2021-09-07 09:31 UTC, in-a-paddy approved these changes

2021-09-07 09:51 UTC, merged